<?xml version="1.0" encoding="UTF-8"?>
<CustomApplication xmlns="http://soap.sforce.com/2006/04/metadata">
    <defaultLandingTab>standard-home</defaultLandingTab>
    <label>test1</label>
    <tab>standard-Account</tab>
    <tab>standard-Campaign</tab>
    <tab>standard-Case</tab>
    <tab>standard-Contact</tab>
    <tab>standard-Contract</tab>
    <tab>standard-Dashboard</tab>
    <tab>standard-Document</tab>
    <tab>standard-Forecasting3</tab>
    <tab>standard-Lead</tab>
    <tab>standard-Opportunity</tab>
    <tab>standard-Order</tab>
    <tab>standard-Product2</tab>
    <tab>standard-report</tab>
    <tab>standard-Solution</tab>
    <tab>standard-Console</tab>
    <tab>standard-Workspace</tab>
    <tab>standard-ContentSearch</tab>
    <tab>standard-ContentSubscriptions</tab>
    <tab>standard-Idea</tab>
    <tab>standard-Knowledge</tab>
    <tab>standard-KnowledgePublishing</tab>
    <tab>standard-ChannelProgram</tab>
    <tab>standard-ChannelProgramLevel</tab>
    <tab>standard-PartnerFundAllocation</tab>
    <tab>standard-PartnerMarketingBudget</tab>
    <tab>standard-PartnerFundClaim</tab>
    <tab>standard-PartnerFundRequest</tab>
    <tab>standard-Scorecard</tab>
    <tab>standard-LiveAgentSupervisor</tab>
    <tab>standard-LiveChatTranscript</tab>
    <tab>standard-LiveChatVisitor</tab>
    <tab>standard-LiveAgentSession</tab>
    <tab>standard-QuickText</tab>
    <tab>standard-UserProfile</tab>
    <tab>standard-OtherUserProfile</tab>
    <tab>standard-CollaborationGroup</tab>
    <tab>standard-File</tab>
    <tab>standard-Chatter</tab>
    <tab>standard-JigsawSearch</tab>
    <tab>standard-Sites</tab>
    <tab>standard-DandBCompany</tab>
    <tab>standard-ProfilePlatformFeed</tab>
    <tab>standard-ProfilePlatformOverview</tab>
    <tab>standard-Coaching</tab>
    <tab>standard-ProfilePlatformCoaching</tab>
    <tab>standard-ProfilePlatformGoals</tab>
    <tab>standard-GoalV2</tab>
    <tab>standard-Metric</tab>
    <tab>standard-AppLauncher</tab>
    <tab>standard-UserProvisioningRequest</tab>
    <tab>standard-StreamingChannel</tab>
    <tab>standard-DuplicateRecordSet</tab>
    <tab>standard-Macro</tab>
    <tab>standard-WorkFeedbackRequest</tab>
    <tab>standard-ProfilePlatformFeedback</tab>
    <tab>standard-WorkPerformanceCycle</tab>
    <tab>standard-Asset</tab>
    <tab>standard-ListEmail</tab>
    <tab>standard-Pricebook2</tab>
    <tab>lvl1__c</tab>
    <tab>lvl2__c</tab>
    <tab>lvl3__c</tab>
    <tab>lvl4__c</tab>
    <tab>lvl5__c</tab>
    <tab>lvl6__c</tab>
    <tab>lvl7__c</tab>
    <tab>lvl10__c</tab>
    <tab>lvl11__c</tab>
    <tab>lvl12__c</tab>
    <tab>lvl8__c</tab>
    <tab>lvl9__c</tab>
    <tab>lvl13__c</tab>
    <tab>lvl14__c</tab>
    <tab>lvl15__c</tab>
    <tab>lvl16__c</tab>
    <tab>lvl17__c</tab>
    <tab>lvl18__c</tab>
    <tab>lvl19__c</tab>
    <tab>lvl20__c</tab>
    <tab>lvl21__c</tab>
    <tab>lvl22__c</tab>
    <tab>udc__Unity_Setup</tab>
    <tab>YS2__Yousign_Api_Key</tab>
    <tab>YS2__Yousign_Api_Key_Lightning</tab>
    <tab>Candidate__c</tab>
    <tab>Property__c</tab>
    <tab>Car__c</tab>
    <tab>Road__c</tab>
    <tab>MyCar__c</tab>
    <tab>PriceBook__c</tab>
    <tab>OwnFiledsComparator__c</tab>
    <tab>Expense__c</tab>
    <tab>lookups</tab>
    <tab>results</tab>
    <tab>Knowledge__kav</tab>
</CustomApplication>
